# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53a316a9d47942260f92b1fc5fcb96673de52f20e820dcb5e9a136db3f595b6903036bb6e9e84db40aff4c36d00934d3112b8c0c69a6bbc9f7269f8ce83988fb

test:
  secret_key_base: 21ac6d523f7aaf931d264dd98f4f17c19457fd299c0c85217a82567d2d80f73b68f5210bf4ca684fc31e58d5e187cd70aeebfbad48a0e373fc8f9bb83cc7e58c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
